//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GigHub.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gig
    {
        public int ID { get; set; }
        public System.DateTime DateTime { get; set; }
        public string Venue { get; set; }
        public string Artist_Id { get; set; }
        public byte Genre_id { get; set; }
    
        public virtual Genre Genre { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
