//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GigHub.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserNotification
    {
        public int id { get; set; }
        public string UserId { get; set; }
        public int NotificationId { get; set; }
        public bool IsRead { get; set; }
        public void Read()
        {
            IsRead = true;
        }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Notification Notification { get; set; }
    }
}
